formations:
- repeat:
    every:
      secs: 10
      nanos: 0
    times: !finite 1
  delay:
    secs: 1
    nanos: 0
  robots: 5
  planning-strategy: only-local
  initial-position:
    shape: !circle
      radius: 25.0
      center:
        x: 0.5
        y: 0.5
    placement-strategy: equal
  waypoints:
  - shape: !circle
      radius: 25.0
      center:
        x: 0.5
        y: 0.5
    projection-strategy: cross
  # - shape: !circle
  #     radius: 40.0
  #     center:
  #       x: 0.5
  #       y: 0.5
  #   projection-strategy: identity
  # waypoint-reached-when-intersects: horizon
  waypoint-reached-when-intersects: current
  # waypoint-reached-when-intersects: !variable 5
