formations:
- repeat:
    every:
      secs: 10
      nanos: 0
    times: !finite 2
  delay:
    secs: 1
    nanos: 0
  robots: 4
  initial-position:
    shape: !circle
      radius: 25.0
      center:
        x: 0.5
        y: 0.5
    placement-strategy: equal
  waypoints:
  - shape: !circle
      radius: 25.0
      center:
        x: 0.5
        y: 0.5
    projection-strategy: cross
