
[workspace]
resolver = "2"
members = ["gbp-rs", "gbpplanner-rs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/AU-Master-Thesis/gbp-rs"
authors = [
    "Jens Høigaard Jensen <jens.jens@live.dk>",
    "Kristoffer Plagborg Bak Sørensen <kristoffer.pbs@tuta.io>",
]
rust-version = "1.75"
license = "MIT"
