[package]
name = "gbp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# anyhow = "1.0.79"
macroquad = "0.4.4"
nalgebra = "0.32.3"
# ndarray = "0.15.6"
# petgraph = "0.6.4"
rayon = "1.8.1"
rstest = "0.18.2"
serde = {version = "1.0.196", features = ["derive"]}
toml = "0.8.8"
thiserror = "1.0.56"
clap = { version = "4.4.18", features = ["derive"] }
color-eyre = "0.6.2"
# bat = "0.24.0"
