
[workspace]
resolver = "2"                                       # Important! wgpu/Bevy needs this!
members = ["factorgraph", "gbp-rs", "gbpplanner-rs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/AU-Master-Thesis/gbp-rs"
authors = [
  "Jens Høigaard Jensen <jens.jens@live.dk>",
  "Kristoffer Plagborg Bak Sørensen <kristoffer.pbs@tuta.io>",
]
rust-version = "1.75"
license = "MIT"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"


# [profile.release]
# codegen-units = 1
# debug = false
# debug-assertions = false
# lto = "fat"
# opt-level = 3
# panic = "abort"
# rpath = false
# strip = true
