formations:
- repeat-every:
    secs: 3
    nanos: 0
  delay:
    secs: 5
    nanos: 0
  robots: 1
  initial-position:
    shape: !line-segment
    - x: 0.45
      y: 0.0
    - x: 0.55
      y: 0.0
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 0.45
      y: 1.25
    - x: 0.55
      y: 1.25
    projection-strategy: identity
- repeat-every:
    secs: 8
    nanos: 0
  delay:
    secs: 1
    nanos: 0
  robots: 3
  initial-position:
    shape: !line-segment
    - x: 0.0
      y: 0.45
    - x: 0.0
      y: 0.55
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 1.25
      y: 0.45
    - x: 1.25
      y: 0.55
    projection-strategy: cross
