formations:
  # red, turn left
- repeat: null
  delay:
    secs: 0
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.05
      y: 0.515
    - x: 0.05
      y: 0.515
    placement-strategy: !random
      attempts: 2000
  waypoints:
  - shape: !line-segment
    - x: 0.54
      y: 0.515
    - x: 0.54
      y: 0.515
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.54
      y: 0.93
    - x: 0.54
      y: 0.93
    projection-strategy: identity
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    # distance: robot-radius
    # intersects-with: horizon
    distance: !meter 10
    intersects-with: !variable 5
  # red, turn left, right, left, right
- repeat: null
  delay:
    secs: 1
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.05
      y: 0.515
    - x: 0.05
      y: 0.515
    placement-strategy: !random
      attempts: 2000
  waypoints:
  - shape: !line-segment
    - x: 0.64
      y: 0.515
    - x: 0.64
      y: 0.515
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.64
      y: 0.655
    - x: 0.64
      y: 0.655
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.84
      y: 0.655
    - x: 0.84
      y: 0.655
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.84
      y: 0.8
    - x: 0.84
      y: 0.8
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.93
      y: 0.8
    - x: 0.93
      y: 0.8
    projection-strategy: identity
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    # distance: robot-radius
    # intersects-with: horizon
    distance: !meter 10
    intersects-with: !variable 5
  # red, turn right
- repeat: null
  delay:
    secs: 2
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.05
      y: 0.515
    - x: 0.05
      y: 0.515
    placement-strategy: !random
      attempts: 2000
  waypoints:
  - shape: !line-segment
    - x: 0.56
      y: 0.515
    - x: 0.56
      y: 0.515
    projection-strategy: identity
  - shape: !line-segment
    - x: 0.56
      y: 0.08
    - x: 0.56
      y: 0.08
    projection-strategy: identity
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    # distance: robot-radius
    # intersects-with: horizon
    distance: !meter 10
    intersects-with: !variable 5

  # start left: turn right (blue)
