# environment = "junction"
environment_image = "junction_twoway"
environment       = "./config/simulations/Complex/environment.yaml"
formation_group   = "./config/simulations/Complex/formation.ron"

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance    = 300.0

[visualisation.uncertainty]
max-radius = 2.5
scale      = 300.0

[visualisation.height]
objects    = 0.5
height-map = 1.0

[visualisation.draw]
robots                             = true
communication-graph                = true
predicted-trajectories             = true
waypoints                          = false
uncertainty                        = false
paths                              = true
generated-map                      = true
height-map                         = false
sdf                                = false
communication-radius               = false
obstacle-factors                   = false
tracking                           = false
interrobot-factors                 = false
interrobot-factors-safety-distance = false
robot-colliders                    = false
environment-colliders              = false
robot-robot-collisions             = true
robot-environment-collisions       = true

[gbp]
sigma-pose-fixed        = 0.000000000000001
sigma-factor-dynamics   = 0.1
sigma-factor-interrobot = 0.01
sigma-factor-obstacle   = 0.01
sigma-factor-tracking   = 0.1
# iterations-per-timestep = 10
lookahead-multiple = 3
[gbp.iteration-schedule]
internal = 20
external = 10
schedule = "interleave-evenly"

[robot]
planning-horizon                       = 5.0
max-speed                              = 7.0
inter-robot-safety-distance-multiplier = 2.2

[robot.radius]
min = 2.0
max = 2.0

[robot.communication]
radius       = 20.0
failure-rate = 0.05

[simulation]
# t0                 = 0.25
max-time           = 10000.0
time-scale         = 1.0
manual-step-factor = 1
hz                 = 20.0
# world-size                                = 100.0
prng-seed                                 = 0
pause-on-spawn                            = false
despawn-robot-when-final-waypoint-reached = false

[rrt]
max-iterations       = 5000000
step-size            = 5.0
collision-radius     = 3.0
neighbourhood-radius = 8.0

[rrt.smoothing]
enabled        = true
max-iterations = 500
step-size      = 0.5


[graphviz.interrobot.active]
style = "dashed"
len   = 8.0
color = "red"

[graphviz.interrobot.inactive]
style = "dashed"
len   = 8.0
color = "gray"

[graphviz]
export-location = "./assets/export/"

[manual]
timesteps-per-step = 1
