formations:
- repeat-every:
    secs: 8
    nanos: 0
  delay:
    secs: 2
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.45
      y: 0.0
    - x: 0.55
      y: 0.0
    placement-strategy: equal
  waypoints:
  - shape: !line-segment
    - x: 0.45
      y: 1.25
    - x: 0.55
      y: 1.25
    projection-strategy: identity
  waypoint-reached-when-intersects:
    distance: robot-radius
    intersects-with: horizon
  finished-when-intersects:
    distance: robot-radius
    intersects-with: horizon
