[package]
name = "min_len_vec"
edition = "2021"
version.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.0"

[lints]
workspace = true
