environment = "junction"
formation_group = "./config/formation.ron"

[visualisation.height]
objects = 0.5
height-map = 1.0

[visualisation.draw]
communication-graph = true
predicted-trajectories = true
waypoints = true
uncertainty = false
paths = false
height-map = false
flat-map = true

[gbp]
sigma-pose-fixed = 0.0000000000000010000000036274937
sigma-factor-dynamics = 0.10000000149011612
sigma-factor-interrobot = 0.009999999776482582
sigma-factor-obstacle = 0.009999999776482582
iterations-per-timestep = 10
lookahead-multiple = 3

[robot]
planning-horizon = 5.0
max-speed = 2.0
dofs = 4
symmetric-factors = true
radius = 1.0

[robot.communication]
radius = 20.0
failure-rate = 0.0

[simulation]
t0 = 0.25
max-time = 10000.0
world-size = 100.0
random-seed = 0

[graphviz.interrobot.edge]
style = "dashed"
len = 8.0
color = "red"

[graphviz]
export-location = "./assets/export/"
