grid = [
    "┬┐ ┌─┐┬ ┬   ┬─┐┬─┐┌─┐┬ ┬ ┬ ┌┐┌┌─┐   ┌─┐┬─┐┌┬┐",
    "├┴┐│ │└┬┘   │ │├┬┘├─┤│││ │ ││││ ┐   ├─┤├┬┘ │ ",
    "┴─┘└─┘┴ ┴   ┴─┘┴└─┴ ┴└┴┘ ┴ ┘└┘└─┘   ┴ ┴┴└─ ┴ ",
]
path-width = 0.8
obstacle-height = 1.0
tile-size = 5.0
