tiles:
  grid:
  - '               '
  - ' ╶─┬─┐┌─────┬┐ '
  - ' ┌─┤┌┤│╷╶──┬┘│ '
  - ' │╷│╵├┤├─┬┬┴┬┤ '
  - ' └┤├─┘││╷╵├─┘│ '
  - ' ╷│╵╷╶┤│├┐└╴┌┘ '
  - ' │├─┴╴│╵│└──┤╷ '
  - ' └┤┌─┐└┬┘┌─┐└┘ '
  - ' ┌┴┤╷├╴│┌┤╷└─┐ '
  - ' │┌┤├┘┌┘││└──┤ '
  - ' ╵│╵├┬┘┌┘└──┐╵ '
  - ' ┌┘╶┘├─┴─┐╷╷└┐ '
  - ' └─┬─┴──┐├┘├─┘ '
  - ' ┌┐│╷┌─╴││╶┘╶┐ '
  - ' │└┼┘├──┘├──┬┤ '
  - ' ╵╶┴─┘╶──┴──┴┘ '
  - '               '
  settings:
    tile-size: 10.0
    path-width: 0.75
    obstacle-height: 1.0
obstacles: []