# environment = "junction"
environment_image = "junction_twoway"
environment       = "./config/simulations/Intersection/environment.yaml"
formation_group   = "./config/simulations/Intersection/formation.ron"

[interaction]
ui-focus-cancels-inputs = true
default-cam-distance    = 100.0

[visualisation.uncertainty]
max-radius = 2.5
scale      = 300.0

[visualisation.height]
objects    = 0.5
height-map = 1.0

[visualisation.draw]
robots                             = true
communication-graph                = false
predicted-trajectories             = false
waypoints                          = true
uncertainty                        = false
paths                              = true
generated-map                      = true
height-map                         = false
sdf                                = true
communication-radius               = false
obstacle-factors                   = false
tracking                           = false
interrobot-factors                 = false
interrobot-factors-safety-distance = false
robot-colliders                    = false
environment-colliders              = false
robot-robot-collisions             = false
robot-environment-collisions       = false


[gbp]
sigma-pose-fixed        = 1e-15
sigma-factor-dynamics   = 0.5
sigma-factor-interrobot = 0.005
sigma-factor-obstacle   = 0.005
sigma-factor-tracking   = 0.01
lookahead-multiple      = 3

[gbp.iteration-schedule]
internal = 50
external = 10
schedule = "interleave-evenly"

[robot]
planning-horizon                       = 2.0
max-speed                              = 15.0
dofs                                   = 4
symmetric-factors                      = true
inter-robot-safety-distance-multiplier = 2.2
# radius            = 1.0
[robot.radius]
min = 2.0
max = 2.0

[robot.communication]
radius       = 20.0
failure-rate = 0.0

[simulation]
max-time                                  = 10000.0
time-scale                                = 1.0
manual-step-factor                        = 1
hz                                        = 10.0
world-size                                = 100.0
prng-seed                                 = 2
pause-on-spawn                            = false
despawn-robot-when-final-waypoint-reached = true

[rrt]
max-iterations       = 1000000
step-size            = 0.5
collision-radius     = 0.1
neighbourhood-radius = 10.0

[rrt.smoothing]
max-iterations = 500
step-size      = 0.5

[graphviz]
export-location = "./assets/export/"

[graphviz.interrobot.active]
style = "dashed"
len   = 8.0
color = "red"

[graphviz.interrobot.inactive]
style = "dashed"
len   = 8.0
color = "gray"


[manual]
timesteps-per-step = 1
