formations:
- repeat:
    every:
      secs: 3
      nanos: 0
    times: !finite 10
  delay:
    secs: 0
    nanos: 500000000
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: -0.05
      y: 0.45
    - x: -0.05
      y: 0.45
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 1.3
      y: 0.45
    - x: 1.3
      y: 0.45
    projection-strategy: identity
  waypoint-reached-when-intersects: horizon

- repeat:
    every:
      secs: 4
      nanos: 0
    times: !finite 10
  delay:
    secs: 0
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: -0.05
      y: 0.55
    - x: -0.05
      y: 0.55
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 1.3
      y: 0.55
    - x: 1.3
      y: 0.55
    projection-strategy: identity
  waypoint-reached-when-intersects: horizon

- repeat:
    every:
      secs: 3
      nanos: 0
    times: !finite 10
  delay:
    secs: 0
    nanos: 500000000
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.45
      y: 1.05
    - x: 0.45
      y: 1.05
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 0.45
      y: -0.3
    - x: 0.45
      y: -0.3
    projection-strategy: identity
  waypoint-reached-when-intersects: horizon

- repeat:
    every:
      secs: 4
      nanos: 0
    times: !finite 10
  delay:
    secs: 0
    nanos: 0
  robots: 1
  planning-strategy: only-local
  initial-position:
    shape: !line-segment
    - x: 0.55
      y: 1.05
    - x: 0.55
      y: 1.05
    placement-strategy: !random
      attempts: 1000
  waypoints:
  - shape: !line-segment
    - x: 0.55
      y: -0.3
    - x: 0.55
      y: -0.3
    projection-strategy: identity
  waypoint-reached-when-intersects: horizon
