tiles:
  grid:
  - '┌┐ ┌──┐'
  - '│├─┤┌─┘'
  - '││ │└─┐'
  - '│└─┴─ │'
  - '└─────┘'
  #
  # - '        '
  # - ' ───┼── '
  # - ' ───┼── '
  # - '  ──┤   '
  # - '        '

  # - '          '
  # - ' ┌─┼─┬─┐┌ '
  # - ' ┼─┘┌┼┬┼┘ '
  # - ' ┴┬─┴┼┘│  '
  # - ' ┌┴┐┌┼─┴┬ '
  # - ' ├─┴┘└──┘ '
  # - '          '

  settings:
    tile-size: 25.0
    path-width: 0.9
    obstacle-height: 1.0
    sdf:
      resolution: 200
      expansion: 0.25
      blur: 0.01
obstacles: []
