[package]
name = "unit_interval"
edition = "2021"
version.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true

[dev-dependencies]
# approx = "0.5"

[lints]
workspace = true
